name: archive
version: 1.0.20
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides encoders and decoders for various archive and compression formats such as zip, tar, bzip2, gzip, and zlib.
homepage: https://github.com/brendan-duncan/archive
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: https://github.com/brendan-duncan/archive/wiki
dependencies:
  crypto: '>=0.9.0 <1.0.0'
dev_dependencies:
  args: '>=0.10.0 <1.0.0'
  browser: any
  test: '>=0.12.0 <1.0.0'
