name: archive
author: Brendan Duncan <brendanduncan@gmail.com>
version: 1.0.5
homepage: http://bitbucket.org/brendan_duncan/archive
description: Provides encoders and decoders for various archive and compression formats, such as zip and tar.
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  crypto: '>=0.9.0 <1.0.0'
dev_dependencies:
  args: any
  unittest: any
